### ISSUE TITLE
Density of Point Feature not working in the latest qgis 3.42

### ISSUE THREAD

**Issue by danjgmoyo** [chjch/pylusat#6]
QGIS version: 3.42.0-Münster
QGIS code revision: feb8023300
Qt version: 5.15.13
Python version: 3.12.9
GDAL version: 3.10.2
GEOS version: 3.13.0-CAPI-1.19.0
PROJ version: Rel. 9.5.1, December 1st, 2024
PDAL version: 2.8.3 (git-version: 56e405)
Algorithm started at: 2025-03-26T13:21:16
Algorithm 'Density of Point Features' starting…
Input parameters:
{ 'AREA_UNIT' : 0, 'INPUT' : 'E:/ngoni/GIS/PROJECTS/galup/GALUP/training/1_lu/datasets/IDUs in the THLD District/THLD_poly.shp', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'OUTPUT_COLUMN' : 'point', 'POINT' : 'E:/ngoni/GIS/PROJECTS/galup/GALUP/training/1_lu/datasets/Education facilities in THLD District/Education_Facilities.shp', 'POP_COLUMN' : '', 'SEARCH_RADIUS' : 0 }

Traceback (most recent call last):
File "C:\Users/Ngoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pylusatq\algorithms\point_den.py", line 172, in processAlgorithm
input_gdf[output_clm] = density.of_point(
^^^^^^^^^^^^^^^^^
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pylusat\density.py", line 110, in of_point
joint_gdf = gpd.sjoin(input_copy, point_gdf, how='left', op='intersects')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\geopandas\tools\sjoin.py", line 110, in sjoin
raise TypeError(f"sjoin() got an unexpected keyword argument '{first}'")
TypeError: sjoin() got an unexpected keyword argument 'op'

Execution failed after 2.27 seconds

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/Ngoni/AppData/Local/Temp/processing_mTjvsA/33075afc56984e7d82334333757fc06d/OUTPUT.gpkg
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
